[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Aumiao"  # æ›¿æ¢ä¸ºä½ çš„é¡¹ç›®åç§°
email = "aumiao@aurzex.top"
version = "2.0.0"    # æ›¿æ¢ä¸ºä½ çš„é¡¹ç›®ç‰ˆæœ¬
authors = [
    {name = "Aumiao Team", email = "aumiao@aurzex.top"},
    {name = "DontLoveBy", email = "laya200900@outlook.com"},
    {name = "Aurzex"},
    {name = "MoonLeaaaf"},
    {name = "Nomen"},
    {name = "MiTao"}
    ]
description = "Aumiao æ˜¯ä¸€æ¬¾é’ˆå¯¹äºç¼–ç¨‹çŒ«ç¤¾åŒºçš„çˆ¬è™«(åˆ’æ‰)

ä½ è¯´çš„å¯¹ï¼Œä½†æ˜¯ã€ŠAumiaoã€‹æ˜¯ä¸€æ¬¾ç”± Aumiao å¼€å‘å›¢é˜Ÿå¼€å‘çš„ç¼–ç¨‹çŒ«è‡ªåŠ¨åŒ–å·¥å…· äº 2023 å¹´ 5 æœˆ 2 æ—¥å‘å¸ƒï¼Œå·¥å…·ä»¥ç¼–ç¨‹çŒ«å®‡å®™ä¸ºèˆå°ï¼Œç©å®¶å¯ä»¥æ‰®æ¼”æ¯›æ¯¡ç”¨æˆ·åœ¨è¿™ä¸ªç­”è¾© ğŸ’© ç¤¾åŒºæ¯›çº¿ ğŸ§¶ åç¼©å¹¶é‚‚é€…å„ç§ä¸åŒçš„ä¹å­äºº ğŸ˜‹ã€‚åœ¨é¢†æ‚Ÿäº†ã€ŠçŒ«ç«™åœ£ç»ã€‹åï¼Œæ‰“è´¥å¼ºæ•Œæ‰«å•æ‰€ ğŸ˜¡ï¼Œåœ¨ç»´æŠ¤ç¼–ç¨‹çŒ«æ ¸é‚ªé“€åˆ çš„å±€é¢çš„åŒæ—¶ï¼Œé€æ­¥æ­å¼€ç¼–ç¨‹çŒ«ç¤¾åŒºçš„çœŸç›¸

å®˜æ–¹ç½‘ç«™:https://aumiao.aurzex.top è”ç³»æˆ‘ä»¬: Aumiao@aurzex.top"

readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "PyQt5",
]

[project.optional-dependencies]
# å¦‚æœæœ‰å¯é€‰ä¾èµ–ï¼Œå¯ä»¥åœ¨è¿™é‡Œåˆ—å‡º
# dev = ["pytest", "black"]

[project.scripts]
# å¦‚æœä½ çš„é¡¹ç›®åŒ…å«å¯æ‰§è¡Œè„šæœ¬ï¼Œå¯ä»¥åœ¨è¿™é‡Œåˆ—å‡º
# my_script = "my_module:main_function"

[tool.setuptools]
# ä½ å¯ä»¥åœ¨è¿™é‡Œæ”¾ç½®setuptoolsç‰¹å®šçš„é…ç½®
# ä¾‹å¦‚ï¼Œä½ å¯ä»¥å®šä¹‰entry pointsæ¥åˆ›å»ºå¯æ‰§è¡Œå‘½ä»¤

[tool.setuptools.packages.find]
# ä½ å¯ä»¥åœ¨è¿™é‡ŒæŒ‡å®šsetuptoolsæŸ¥æ‰¾åŒ…çš„æ–¹å¼
# where = ["src"]  # å‡è®¾ä½ çš„åŒ…åœ¨srcç›®å½•ä¸‹
exclude = ["tests*"]  # æ’é™¤æµ‹è¯•ç›®å½•
